"""keys table

Revision ID: 2de057e0d16e
Revises: 
Create Date: 2018-07-09 16:52:21.878372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de057e0d16e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key',
    sa.Column('Round', sa.Integer(), nullable=False),
    sa.Column('Prob', sa.String(length=120), nullable=False),
    sa.Column('Key', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('Round', 'Prob')
    )
    op.create_index(op.f('ix_key_Key'), 'key', ['Key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_key_Key'), table_name='key')
    op.drop_table('key')
    # ### end Alembic commands ###
